---
title: "Se reporter aux termes de la convention signée avec le partenaire financeur"
description: "TODO rédiger."
warning: "ATTENTION : les textes source, s'ils sont protégés par un droit d'auteur, ne peuvent pas être diffusés."