---
title: "Diffusion  autorisée, mais  réutilisation interdite"
description: "TODO rédiger."
warning: "ATTENTION : Les données seront disponibles à la consultation, mais ne pourront pas être réutilisées, pour quelque usage que ce soit, grâce à la mention 'tous droits réservés' qui sera attachée aux données. Assurerez-vous qu'il est impossible ou très difficile de ré-identifier les personnes "
