---
title: "Interdiction de diffusion sans l'autorisation des co-auteurs"
description: "TODO rédiger."
warning: "ATTENTION : les textes source, s'ils sont protégés par un droit d'auteur, ne peuvent pas être diffusés."