---
title: "Diffusion des données sous licence libre possible"
description: "Les données appartiennent à votre employeur."
warning: "ATTENTION : assurez-vous d'avoir obtenu l'autorisation de diffusion de vorte employeur."