---
title: "Vous pouvez attribuer la licence de votre choix"
description: "Proposer l'éventail des licences Creative Commons."
warning: "ATTENTION : les textes source, s'ils sont protégés par un droit d'auteur, ne peuvent pas être diffusés."