---
title: "Obligation de diffusion des données sous licence ouverte ou ODBL"
description: "TODO: rédiger"
warning: "ATTENTION : les textes source, s'ils sont protégés par un droit d'auteur, ne peuvent pas être diffusés."