---
question: "Vos données sont :"
answers:
  - text: "Des données personnelles"
    target: "dtn_personal_data"
  - text: "Des données collectées sur internet"
    target: "dtn_scraped_data"
  - text: "Des données sensibles (secret défense, industriel, etc.)"
    target: "anode_entity_autor_required"
  - text: "Des données issues du Text and data mining"
    target: "dtn_private_founding"
  - text: "Des photos"
    target: "dtn_photos"
  - text: "Des notes, carnets de terrain, textes manuscrits, articles de presse, …"
    target: "dtn_texts"
  - text: "Des enregistrements audio ou vidéo"
    target: "dtn_audio_video"
  - text: "Des données issues d'un fonds d'archives"
    target: "dtn_archival"
  - text: "Des entretiens"
    target: "dtn_interviews"
