---
question: "Avez-vous obtenu un financement privé pour la production de ces données ?"
answers:
  - text: "Oui"
    target: "dtn_private_founding_share_text"
  - text: "Non"
    target: "anode_open_license_odbl"
